name: Docker Registry Cleanup

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  docker:
    name: Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Docker Cleanup
        uses: lostlink/docker-cleanup@v1.0.1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repositories: megalinter-custom-flavor-all-megalinter-custom-flavor
          protected-tags: beta

  ghcr:
    name: GitHub Container Registry
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: GitHub Container Registry Cleanup
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          token: ${{ github.token }}
          cut-off: 1month
          image-names: megalinter-custom-flavor-all/megalinter-custom-flavor
